version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/e8u

hooks:
  ApplicationStop:
    - location: bin/app-stop
      timeout: 10
      runas: ec2-user

  AfterInstall:
     - location: bin/install-pkgs
       timeout: 1200
       runas: ec2-user

  ApplicationStart:
    - location: bin/app-start
      timeout: 60
      runas: ec2-user

  ValidateService:
    - location: bin/app-validate
      timeout: 10
      runas: ec2-user
